---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dp-innsyn
  description: Tilbyr innsyn til bruker for hva som skjer med dagpenger
spec:
  type: service
  lifecycle: production
  owner: teamdagpenger
  system: dp-soknadsdialog
  providesApis:
    - dp-innsyn-api
  dependsOn:
    - resource:dp-innsyn-db
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dp-innsyn-api
  description: Gir informasjon om søknader
spec:
  type: openapi
  lifecycle: production
  owner: teamdagpenger
  system: dp-soknadsdialog
  definition: |
    openapi: 3.0.0
    info:
      title: dp-innsyn
      description: Gir innsyn i Dagpenger
      version: 0.0.1
    servers:
      - url: http://dp-innsyn/api
        description: Produksjon, in-cluster
    paths:
      /soknad:
        get:
          summary: Returnerer en liste med søknader
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
      /vedtak:
        get:
          summary: Returnerer en liste med vedtak
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dp-innsyn-db
  description: Lagrer data om brukers behandlinger i NAV
spec:
  type: database
  owner: teamdagpenger
  system: dp-soknadsdialog
