apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-innsyn"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/isalive"
  readiness:
    path: "/isready"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  env:
    - name: KAFKA_RAPID_TOPIC
      value: private-dagpenger-behov-v2
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-innsyn
    - name: KAFKA_RESET_POLICY
      value: earliest
  envFrom:
    - configmap: kafka-bootstrap-servers
  filesFrom:
    - secret: serviceuser-srvdp-innsyn
      mountPath: "/var/run/secrets/nais.io/service_user"
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
