apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-innsyn"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/isalive"
  readiness:
    path: "/isready"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: dp-dagpenger
        - application: dp-soknad-veileder
        - application: veientilarbeid
          namespace: paw
        - application: paw-auth-proxy
          namespace: paw
        - application: bakveientilarbeid
          namespace: paw
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - name: dp-innsyn
        type: POSTGRES_12
        tier: {{ db_tier }}
        diskType: SSD
        highAvailability: false
        diskSize: {{ db_size }}
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: innsyn
            envVarPrefix: DB
        cascadingDelete: false
