apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-innsyn"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/isalive"
  readiness:
    path: "/isready"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  kafka:
    pool: {{ kafka_pool }}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: dp-dagpenger